version: '3'
services:
  apiproj_redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
  apiproj_api:
    image: apiproj:latest
    command: uvicorn api:app --host 0.0.0.0 --port 5057
    ports:
      - "5057:5057"
    depends_on:
      - apiproj_redis
    links:
      - apiproj_redis
  apiproj_worker:
    image: apiproj:latest
    command: rq worker --url redis://apiproj_redis:6379 my_queue
    depends_on:
      - apiproj_redis
    links:
      - apiproj_redis
